# Generated by Django 3.2 on 2023-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='family/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('is_standby', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_standby', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='sample/')),
                ('name', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('is_standby', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
