# Generated by Django 3.2 on 2023-03-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_standby',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_standby',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_standby',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='family/'),
        ),
        migrations.AlterField(
            model_name='family',
            name='text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
