# Generated by Django 3.2 on 2025-12-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_lineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='account',
            field=models.CharField(default='dev', max_length=50),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='lineuser',
            unique_together={('account', 'name'), ('account', 'user_id')},
        ),
    ]
