# Generated by Django 3.2 on 2023-03-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_gallery_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='gallery/'),
        ),
    ]
