# Generated by Django 3.2 on 2023-03-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='family/')),
                ('title', models.TextField(max_length=100)),
                ('text', models.TextField(max_length=300)),
            ],
        ),
    ]
