# Generated by Django 3.2 on 2023-03-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(default='sample_name', max_length=15),
        ),
    ]
