# Generated by Django 3.2 on 2023-03-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_sample_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.FileField(upload_to='gallery/'),
        ),
    ]
